### ISSUE TITLE
Version 2.0 of the NIST beacon

### ISSUE THREAD

**Issue by urda** [urda/py_nist_beacon#23]
Just saw the following notice:

**Version 2.0 of the NIST beacon is planned to be deployed in the Summer of 2017. This version will make significant changes to the REST interface.**

I have no idea how this will impact the project.

Source: https://beacon.nist.gov/home

**Comment by urda** [comment]
Removing `bug` and `chore` states, as I think this will be more of feature, and we will have major version numbers to work from.

**Comment by urda** [comment]
Closing this out for now until we have an actual 2.0 version to build against.

---

```
MIME-Version: 1.0
Received: REDACTED
Date: REDACTED
Delivered-To: REDACTED
Message-ID: REDACTED
Subject: Version 2.0 of the NIST BEACON API ?
From: Peter Urda <***@***.***>
To: "Peralta, Rene" <rene.peralta@nist.gov>
Content-Type: multipart/alternative; boundary="f403045c21cc46b4510559565603"

--f403045c21cc46b4510559565603
Content-Type: text/plain; charset="UTF-8"

We're approaching the end of summer. Is there a roadmap for release of
version 2.0 ?

~ Peter Urda

http://urda.cc

--f403045c21cc46b4510559565603
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">We&#39;re approaching the end of summer. Is there a roadma=
p for release of version 2.0 ?<br><div><br clear=3D"all"><div><div class=3D=
"gmail_signature" data-smartmail=3D"gmail_signature"><div dir=3D"ltr"><div>=
<div dir=3D"ltr"><div><div dir=3D"ltr">~ Peter Urda<br><br></div><div><a hr=
ef=3D"http://urda.cc" target=3D"_blank">http://urda.cc</a></div></div></div=
></div></div></div></div>
</div></div>

--f403045c21cc46b4510559565603--
```

**Comment by nealmcb** [comment]
What is the status of this, as of 2021?

Version 1.0 seems to have stopped working in 2018.....
Thanks!

**Comment by urda** [comment]
Hey @nealmcb i am not sure when I will be able to upgrade against the newer API. Since I joined Amazon a lot of my free time has been lost to work!

I recently started moving automated testing and tooling into GitHub actions, so I can't give a timeline at this time but it's still something I want to tinker with later this year.

**Comment by nealmcb** [comment]
Yeah - I get it. Thanks for the quick response.
Can you re-open this issue?
And kudos on having opened it very early on!

**Comment by urda** [comment]
@nealmcb I will either re-open this or track it in a new issue.

I'll plan on doing something like I did with https://github.com/urda/django-letsencrypt/issues/95 where I replanned and updated the project.
